import {projects,featuredProjects,groups,notes,social} from './content.mjs';
import {seoHead,writeDiscovery} from './seo.mjs';
import { mkdir, writeFile, readFile } from 'node:fs/promises';
import { fileURLToPath } from 'node:url';
const root = fileURLToPath(new URL('../', import.meta.url));
const e=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));

const icons={external:'<path d="M10 7H7a5 5 0 0 0 0 10h3m4-10h3a5 5 0 0 1 0 10h-3M8 12h8"/>',book:'<path d="M3 5h6l3 2 3-2h6v14h-6l-3 2-3-2H3ZM12 7v14M6 9h3m-3 4h3m6-4h3m-3 4h3"/>',back:'<path d="m12 5-7 7 7 7M5 12h14"/>',search:'<circle cx="10.8" cy="10.8" r="6.8"/><path d="m16 16 4.5 4.5"/>',close:'<path d="m6 6 12 12M6 18 18 6"/>',notes:'<rect x="5" y="3" width="14" height="18" rx="2"/><path d="M9 8h6M9 12h6M9 16h4"/>'};
const icon=(name)=>`<svg class="ui-icon" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.8" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true">${icons[name]}</svg>`;
const crestPaths={forest:'<path d="M29 12h6v7h6v7h6v7h-9v7h12v7H35v9h-6v-9H14v-7h12v-7h-9v-7h6v-7h6Z"/>',fire:'<path d="M32 12h6v12h6v6h6v18h-6v6H20v-6h-6V30h6v6h6V24h6Z"/>',water:'<path d="M14 25h12v-6h12v6h12v6H38v-6H26v6H14m0 12h12v-6h12v6h12v6H38v-6H26v6H14"/>'};
const crest=kind=>`<div class="banner-crest" aria-hidden="true"><svg viewBox="0 0 64 70" fill="none" stroke="currentColor" stroke-width="1.4" stroke-linecap="round" stroke-linejoin="round">${crestPaths[kind]}</svg></div>`;
const brandArt={'number-company':'number-company-logo.png','icon-emulator':'icon-emulator-logo.svg','larpmegle':'larpmegle-logo.svg'};
const projectStats={'icon-emulator':[['7.9K','images created'],['1.1K','training trees'],['540+','export requests']],'larpmegle':[['13k','games'],['#1','in search ranking']]};
const stats=p=>projectStats[p.slug]?`<section class="sample-stats" aria-label="Project statistics"><dl style="--stat-count:${projectStats[p.slug].length}">${projectStats[p.slug].map(([value,label])=>`<div><dt>${label}</dt><dd>${value}</dd></div>`).join('')}</dl></section>`:'';
const commandButton=()=>`<button class="command-trigger" type="button" aria-label="Open command menu" aria-haspopup="dialog">${icon('search')}<span>search</span><kbd class="modifier">ctrl</kbd><kbd>k</kbd></button>`;
const captures={
 'icon-emulator':{file:'icon-emulator-capture.png',width:614,height:576,alt:'Icon Emulator branching workspace with dice and clover icons'},
 'larpmegle':{file:'larpmegle-capture.png',width:367,height:239,alt:'Larpmegle video debate with two players, winner controls, and a judge'}
};
function artwork(p,detail=false){
 if(!p.art)return '<div class="archive-art"><span>project archive</span></div>';
 const generated=`<img class="project-image ${p.theme}" src="/assets/${p.art}" alt="${e(p.alt||p.title+' project artwork')}" ${detail?'fetchpriority="high"':'loading="lazy"'} width="1536" height="1024">`;
 const capture=captures[p.slug];
 if(detail||!capture)return generated;
 return `<div class="art-split ${p.theme}">${generated}<div class="capture-side"><img src="/assets/${capture.file}" alt="${e(capture.alt)}" width="${capture.width}" height="${capture.height}" loading="lazy" decoding="async"></div></div>`;
}
function rail(active=''){return `<aside class="project-rail banner banner-water" aria-label="Software projects and notes">${crest('water')}<div class="rail-heading"><h2>software projects</h2></div><nav class="project-list" aria-label="Software projects">${featuredProjects.filter(p=>p.slug!=='number-company').map((p,i)=>`<a class="project-entry ${p.theme} ${active===p.slug?'active':''}" href="/${p.slug}/" ${active===p.slug?'aria-current="page"':''}><div class="project-art">${artwork(p)}</div><div class="project-caption"><img class="company-logo" src="/assets/${brandArt[p.slug]}" alt="" width="36" height="36"><div><h3>${e(p.title)}</h3><p>${e(p.short)}</p></div><span class="open-project">${icon('book')}<span>Open project</span></span></div>${stats(p)}</a>`).join('')}</nav><section class="notes" id="notes"><h2>project notes</h2><div class="note-board">${notes.map(n=>`<a class="note-link" href="/notes/${n.slug}/"><time>${n.date}</time><span class="note-title">${e(n.title)}</span>${icon('book')}</a>`).join('')}</div></section><footer><p>layout inspired by my friend <a href="https://jame.li" target="_blank" rel="noopener noreferrer">james li ${icon('external')}</a></p><p>made for sammy hawari · 2026</p></footer></aside>`;}
const dialog=`<dialog id="command-dialog" aria-labelledby="command-title"><div class="command-head"><h2 id="command-title">search</h2><button type="button" class="close-command" aria-label="Close command menu">${icon('close')}</button></div><label class="sr-only" for="command-search">Search pages and links</label><input id="command-search" type="search" placeholder="find a project, note, or link…" autocomplete="off" spellcheck="false"><div class="command-results" aria-label="Search results"></div><p class="command-help">Arrow keys to navigate <span>Enter to open · Esc to close</span></p></dialog>`;
function home(){return `<main id="main-content" class="profile">
 <header class="name-panel"><a class="name" href="/" aria-label="Sammy Hawari home">sammy hawari <span lang="ar" dir="rtl">سامي هواري</span></a>${commandButton()}</header>
 <div class="profile-grid">
  <section class="about-panel banner banner-forest" aria-labelledby="about-title">${crest('forest')}
   <div><p class="eyebrow">software developer</p><h1 id="about-title">hi, i’m<br> sammy.</h1><p class="about-copy">i build websites and tools for creating game art.</p><p class="location">waterloo, ontario</p></div>
   <section class="school" aria-labelledby="school-heading"><div class="school-heading"><h2 id="school-heading">laurel heights</h2><span class="school-year">gr 12 <span>[senior]</span></span></div><p class="school-type">secondary school</p><ul class="school-highlights"><li><strong>Computer Science Club</strong><span>President</span></li><li><strong>Cyber Security Club</strong><span>Executive &amp; Founding Member</span></li><li><strong>CEMC Canadian Computing Competition</strong><span>Distinction</span></li><li><strong>Kiwanis Music Festival</strong><span>School Band Trophy &amp; 3× Gold Medalist · Bassist</span></li></ul></section>
   <section class="work-section" aria-labelledby="work-heading"><h2 id="work-heading">work:</h2><a class="work-entry" href="https://www.yupp.ai/" target="_blank" rel="noopener noreferrer"><span class="work-logo"><img src="/assets/yupp-favicon.png" alt="" width="32" height="32"></span><span class="work-info"><strong>Yupp</strong><span>Data Science Intern</span></span></a></section>
   <section class="recent-section" aria-labelledby="recent-heading"><h2 id="recent-heading">recently:</h2><ul class="recent-updates"><li>won <strong>Most Creative Game</strong> at <a class="inline-brand recent-brand" href="https://campfire.hackclub.com/" target="_blank" rel="noopener noreferrer"><img src="/assets/campfire-favicon.png" alt="" width="16" height="16"><span>Campfire</span></a></li><li>won <strong>Best Solo Project</strong> at <a class="inline-brand recent-brand" href="https://campfire.hackclub.com/" target="_blank" rel="noopener noreferrer"><img src="/assets/campfire-favicon.png" alt="" width="16" height="16"><span>Campfire</span></a></li><li><strong>1st Place Overall Winner</strong> at <a class="inline-brand recent-brand" href="https://neoleague.dev/" target="_blank" rel="noopener noreferrer"><img src="/assets/neo-league-logo.png" alt="" width="19" height="19"><span>Neo Dev League</span></a><span class="recent-subnote">I now help organize this competition. 😆</span></li></ul><a class="detail-link resume-link" href="https://drive.google.com/file/d/1FP-2wuKHYGQZ9-R-1TcYRiEtbJVqUCnD/view?usp=sharing" target="_blank" rel="noopener noreferrer">${icon('notes')}<span>VIEW MY RESUME</span></a></section><div class="meadow-vignette forest-vignette" aria-hidden="true"></div>
  </section>
  <div class="middle-column banner banner-fire">${crest('fire')}
   <section class="number-demo" aria-labelledby="number-demo-heading"><header class="demo-heading"><img class="company-logo" src="/assets/number-company-logo.png" alt="" width="32" height="32"><h2 id="number-demo-heading">the number company</h2></header><div class="product-stage"><svg class="arcade-frame" viewBox="0 0 400 340" preserveAspectRatio="none" aria-hidden="true"><defs><linearGradient id="arcade-colours" x1="0" y1="0" x2="1" y2="1"><stop offset="0" stop-color="#ff7185"/><stop offset=".2" stop-color="#ffbe58"/><stop offset=".4" stop-color="#eee879"/><stop offset=".6" stop-color="#7de5ac"/><stop offset=".8" stop-color="#70c4ff"/><stop offset="1" stop-color="#d1a0ff"/></linearGradient></defs><rect class="arcade-rainbow arcade-halo" x="4" y="4" width="392" height="332" pathLength="1000"/><rect class="arcade-rainbow" x="4" y="4" width="392" height="332" pathLength="1000"/></svg><div class="storefront-preview" aria-label="Live preview of the numbered shirt"><iframe class="storefront-frame" data-preview-src="http://127.0.0.1:3000/shop" title="Live numbered shirt preview" tabindex="-1" inert sandbox="allow-scripts allow-same-origin" referrerpolicy="no-referrer"></iframe><div class="preview-fallback"><img src="/assets/number-company.webp" alt="The Number Company white numbered shirt" width="400" height="400"><p class="preview-status" role="status">Loading storefront preview…</p></div><a class="preview-open" href="http://127.0.0.1:3000/" target="_blank" rel="noopener noreferrer" aria-label="Open The Number Company website"></a></div><div class="purchase-dock-local"><a class="storefront-link purchase-button" href="http://127.0.0.1:3000/shop" target="_blank" rel="noopener noreferrer"><svg class="purchase-outline" viewBox="0 0 200 54" preserveAspectRatio="none" aria-hidden="true"><path class="drawn-button-edge" d="M10 4C52 1 143 5 191 3c5 13 2 32 3 47-50 3-133-2-188 1C3 35 7 18 10 4Z"/><path class="drawn-button-highlight" pathLength="100" stroke-dasharray="8 42" d="M168 9H183Q188 9 188 14V41Q188 46 183 46H15Q10 46 10 41V14Q10 9 15 9H168Z"/></svg><span class="purchase-label">Purchase Shirt</span><span class="purchase-price">$29 USD</span></a></div></div><div class="demo-copy"><p>I sell regular t-shirts, but each time one is sold the number on the next shirt goes up!</p><a class="detail-link" href="/number-company/">project details ${icon('book')}</a></div></section>
   <section id="roblox" class="roblox-panel" aria-labelledby="roblox-title"><img class="roblox-emblem" src="/assets/roblox-studio-emblem.png" width="500" height="500" alt="" aria-hidden="true"><h2 id="roblox-title">roblox studios</h2><div class="group-list">${groups.map(g=>`<a class="group-item" href="${g.url}" target="_blank" rel="noopener noreferrer"><img src="/assets/${g.art}" alt="" width="44" height="44"><div><h3>${g.name} ${icon('external')}</h3><p class="studio-role">Founder &amp; Lead Developer</p><p class="studio-stat">${g.prefix||''}<strong>${g.stat}</strong> ${g.description}</p></div></a>`).join('')}</div></section>
   <nav class="social-panel" aria-label="Social links"><div class="social-identity"><span class="social-handle">@mindlesstruffle</span><span class="social-discord">discord <strong>chatgpt9</strong></span></div>${social.map(([name,url])=>{const brand=name==='github'?'github':name==='linkedin'?'linkedin':'x';return `<div class="social-station" data-social="${brand}"><div class="social-motion"><a class="social-key ${brand}" href="${url}" aria-label="Sammy on ${name}" target="_blank" rel="noopener noreferrer"><img src="/assets/icons/${brand}.svg" alt="" width="32" height="32"><span class="social-tooltip">${name}</span></a></div><canvas class="social-particles" width="88" height="44" aria-hidden="true"></canvas></div>`}).join('')}</nav>
  </div>
 </div></main>`;}

function project(p){return `<main id="main-content" class="detail"><div class="detail-nav"><a href="/" class="back-link">${icon('back')}back</a>${commandButton()}</div><article><header class="detail-heading"><p class="eyebrow">${e(p.type)}</p><h1>${e(p.title)}</h1></header><div class="detail-art ${p.theme}">${artwork(p,true)}</div>${p.link?`<p class="project-external"><a href="${p.link}" target="_blank" rel="noopener noreferrer">${p.label} ${icon('external')}</a></p>`:''}<p class="intro">${e(p.intro)}</p>${stats(p)}<dl class="project-facts"><div><dt>focus</dt><dd>${e(p.type.split(' · ')[0])}</dd></div><div><dt>tools & ideas</dt><dd>${e(p.stack)}</dd></div></dl>${p.sections.map(([title,body])=>`<section><h2>${e(title)}</h2><p>${e(body)}</p></section>`).join('')}<a class="back-link detail-signoff" href="/">${icon('back')}sammy hawari</a></article></main>`;}
function note(n){return `<main id="main-content" class="detail"><div class="detail-nav"><a class="back-link" href="/">${icon('back')}back</a>${commandButton()}</div><article class="note-article"><header class="detail-heading"><p class="eyebrow">${n.date} · project notes</p><h1>${e(n.title)}</h1></header>${n.body.map(([h,p])=>`<section><h2>${e(h)}</h2><p>${e(p)}</p></section>`).join('')}<p><a class="text-link" href="/${n.project}/">visit the project ${icon('external')}</a></p></article></main>`;}
function doc(title,description,content,active='',pagePath=active?active+'/':''){return `<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1"><meta name="theme-color" content="#315441">${seoHead(pagePath)}<link rel="icon" href="/assets/sammy-s-favicon-32.png" type="image/png" sizes="32x32"><link rel="icon" href="/assets/sammy-s-logo.svg" type="image/svg+xml" sizes="any"><link rel="apple-touch-icon" href="/assets/apple-touch-icon.png" sizes="180x180"><link rel="stylesheet" href="/assets/fonts.css"><link rel="stylesheet" href="/assets/indie-fonts.css"><link rel="stylesheet" href="/assets/medieval.css"><link rel="stylesheet" href="/assets/pixel-fonts.css"><link rel="stylesheet" href="/assets/pixel-banners.css"><link rel="stylesheet" href="/assets/banner-details.css"><link rel="stylesheet" href="/assets/adventure-ui.css"><link rel="stylesheet" href="/assets/social-particles.css"><link rel="stylesheet" href="/assets/cursor-vines.css"><link rel="stylesheet" href="/assets/project-compositions.css"><link rel="stylesheet" href="/assets/scene-depth.css"><script src="/assets/app.js" defer></script><script type="module" src="/assets/creature-motion.js"></script><script type="module" src="/assets/scene-depth.js"></script><script type="module" src="/assets/social-particles.js"></script><script type="module" src="/assets/cursor-vines.js"></script><script type="module" src="/assets/rainbow-cursor.js"></script><script type="module" src="/assets/sword-tear.js"></script></head><body><a class="skip-link" href="#main-content">skip to content</a><div class="site-shell">${content}${rail(active)}</div>${dialog}</body></html>`;}
async function save(path,html){await mkdir(root+'dist/'+path,{recursive:true});await writeFile(root+'dist/'+path+'index.html',html);}
await save('',doc('Sammy Hawari · portfolio','Sammy Hawari, a software developer and Laurel Heights Secondary School student in Waterloo, Ontario. Websites, creative tools, and games.',home()));
for(const p of projects)await save(p.slug+'/',doc(`${p.title} · sammy hawari`,p.intro,project(p),p.slug));
for(const n of notes)await save('notes/'+n.slug+'/',doc(`${n.title} · sammy hawari`,n.body[0][1],note(n),'',`notes/${n.slug}/`));
await writeFile(root+'dist/404.html',doc('page not found · sammy hawari','This page could not be found.',`<main id="main-content" class="detail"><article><h1>page not found.</h1><p>this page is no longer available.</p><a class="back-link" href="/">${icon('back')}home</a></article></main>`,'','404.html'));
await writeFile(root+'dist/assets/search.json',JSON.stringify([{title:'home',url:'/',group:'links',shortcut:'shift + 0'},...social.map(([title,url])=>({title,url,group:'links',shortcut:title==='linkedin'?'shift + 1':title==='github'?'shift + 2':'shift + 3'})),...featuredProjects.map(p=>({title:p.title,url:`/${p.slug}/`,description:p.short,group:'software projects'})),...groups.map(g=>({title:g.name,url:g.url,description:'Founder and Lead Developer · '+g.stat+' '+g.description,group:'roblox'})),...notes.map(n=>({title:n.title,url:`/notes/${n.slug}/`,group:'project notes'}))]));
await writeDiscovery(root+'dist');
console.log('Built portfolio, project pages, project notes, and command search. Localhost only.');
